connections = 
{

    /pl_rtl/abm_and_smem/abm_and_smem_ctl/S_AXI                        bdc/sources_1/bd/abm_and_smem/src/abm_and_smem_ctl.v         REG 
    /pl_rtl/abm_and_smem/chipif_cdc/clock_manager/clock_mgr_ctl/S_AXI  bdc/sources_1/bd/abm_and_smem/src/clock_mgr/clock_mgr_ctl.v  CHIP
    /pl_rtl/axi_intc_0/S_AXI      
    /pl_rtl/axi_revision/S_AXI
    /pl_rtl/adc_bank/axi_adc_bank/S_AXI                                project/src/ltc1867/axi_adc_bank.v                           REG
    /pl_rtl/chip_power_ctl/S_AXI                                       project/src/chip_power_ctl.v                                 REG

    /frame_gen/framegen_ctl/S_AXI
    /mindy_core/mindy_core_ctl/S_AXI                            bdc/sources_1/bd/mindy_core/src/mindy_core_ctl.v             MC 
    /indy_lvds/lvds_source/sensor_emu/sensor_emu_ctl_axi/S_AXI  bdc/sources_1/bd/indy_lvds/src/sensor_emu_ctl_axi.v          SEMU
    /indy_lvds/lvds_ctl/S_AXI                                   bdc/sources_1/bd/indy_lvds/src/lvds_ctl.v                    LVDS

}

