//--------------------------------------------------------------------------------------------------------------
// Autogenerated file -- DO NOT EDIT
//
// This header contains:
// * Register and register field specifiers for B0 chip
// * Functions for reading and writing 32-bit registers or fields, depending on the specifier provided
// * Functions for inserting and extracting field values from 32-bit ints
// * Introspection functions (look up ASCII register name given a specifier, or vice versa)
//
// Specifiers are 64-bit unsigned integer constants with the following structure:
//    bits 63:56 : If specifier is a field, field width in bits.
//    bits 55:48 : If specifier is a field, field offset in bits.
//    bits 47:0  : Register address (usually relative to a base address).
// If the field width and offset are both 0, the specifier is a whole-register specifier, and may be
// treated as an address.
//--------------------------------------------------------------------------------------------------------------

#ifndef _B0_CHIP_REG_H
#define _B0_CHIP_REG_H

#include <stdint.h>

// Macros to extract fields from register specifier constants
#define CHIP_RS_IS_FIELD(spec)    (((uint64_t)(spec) & 0xffff000000000000ULL) != 0ULL)
#define CHIP_RS_GET_ADDRESS(spec) (((uint64_t)(spec) & 0x0000ffffffffffffULL)        )
#define CHIP_RS_GET_WIDTH(spec)   (((uint64_t)(spec) >> 56) & 0xffULL)
#define CHIP_RS_GET_OFFSET(spec)  (((uint64_t)(spec) >> 48) & 0xffULL)

//
// Returns a version of register_value modified by setting the field described by specifier to field_value.
//
uint32_t chipreg_setfield(uint32_t register_value, uint64_t specifier, uint32_t field_value);

//
// Return the field described by specifier from register_value.
//
uint32_t chipreg_getfield(uint32_t register_value, uint64_t specifier);

//
// Return the ASCII name corresponding to a register or field specifier, or NULL if the specifier is invalid.
//
const char * chipreg_specifier_to_regname(uint64_t specifier);

//
// Return the specifier corresponding to an ASCII name, or 0xffffffffffffffffULL if the name is invalid.
//
uint64_t chipreg_regname_to_specifier(const char *name);


//--------------------------------------------------------------------------------------------------------------
// REGISTER / FIELD SPECIFIER CONSTANTS
//--------------------------------------------------------------------------------------------------------------

//
// Register:    CHIP_ID
// Description: Chip Identification

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     chip_id                        32  31:00 RO   0x0         CHIP Identification
//
#define CHIP_ID                                                      0x0000000000000000ULL
#define CHIP_ID_chip_id                                              0x2000000000000000ULL

//
// Register:    CHIP_REV
// Description: Chip Revision

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     chip_rev                       32  31:00 RO   0x0         CHIP Revision
//
#define CHIP_REV                                                     0x0000000000000004ULL
#define CHIP_REV_chip_rev                                            0x2000000000000004ULL

//
// Register:    CHIP_RESET
// Description: Chip Reset

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     chip_reset                     1       0 RW   0x0         Full-Chip Master reset
//     spi0_reset                     1       1 RW   0x0         Reset SPI0 Block
//     spi1_reset                     1       2 RW   0x0         Reset SPI1 Block
//     cfg_reset                      1       3 RW   0x0         Reset Configuration registers
//     otp_reset                      1       4 RW   0x0         Reset OTP Block
//     gpio_reset                     1       5 RW   0x0         Reset GPIO Block
//     tctl_reset                     1       6 RW   0x0         Reset TCTL Block
//     weep_reset                     1       7 RW   0x0         Reset WEEP Block
//     bank_reset                     8   15:08 RW   0x0         Reset bank
//     sensor_reset                   8   23:16 RW   0x0         Reset Sensor
//     reserved2                      8   31:24 RO   0x0         Reserved
//
#define CHIP_RESET                                                   0x0000000000000020ULL
#define CHIP_RESET_chip_reset                                        0x0100000000000020ULL
#define CHIP_RESET_spi0_reset                                        0x0101000000000020ULL
#define CHIP_RESET_spi1_reset                                        0x0102000000000020ULL
#define CHIP_RESET_cfg_reset                                         0x0103000000000020ULL
#define CHIP_RESET_otp_reset                                         0x0104000000000020ULL
#define CHIP_RESET_gpio_reset                                        0x0105000000000020ULL
#define CHIP_RESET_tctl_reset                                        0x0106000000000020ULL
#define CHIP_RESET_weep_reset                                        0x0107000000000020ULL
#define CHIP_RESET_bank_reset                                        0x0808000000000020ULL
#define CHIP_RESET_sensor_reset                                      0x0810000000000020ULL
#define CHIP_RESET_reserved2                                         0x0818000000000020ULL

//
// Register:    CHIP_CLOCK1
// Description: Chip Clock Control 1

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank_sysclk_dis                8   07:00 RW   0x0         Disable System Clock To Banks
//     bank_lvdsclk_dis               8   15:08 RW   0x0         Disable LVDS Clock To Banks
//     lvds_int_byp                   8   23:16 RW   0x0         Bypass LVDS clock, using SYSCLK
//     weep_clk_div_ratio             3   26:24 RW   0x0         Bypass LVDS clock, using SYSCLK
//     reserved                       5   31:27 RO   0x0         Reserved
//
#define CHIP_CLOCK1                                                  0x0000000000000028ULL
#define CHIP_CLOCK1_bank_sysclk_dis                                  0x0800000000000028ULL
#define CHIP_CLOCK1_bank_lvdsclk_dis                                 0x0808000000000028ULL
#define CHIP_CLOCK1_lvds_int_byp                                     0x0810000000000028ULL
#define CHIP_CLOCK1_weep_clk_div_ratio                               0x0318000000000028ULL
#define CHIP_CLOCK1_reserved                                         0x051b000000000028ULL

//
// Register:    GPIO_CTRL
// Description: GPIO control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select                         16  15:00 RW   0x0         For every GPIO configured as an output, select source A or
//                                                               B:
//     direction                      16  31:16 RW   0x0         GPIO direction:
//
#define GPIO_CTRL                                                    0x0000000000000040ULL
#define GPIO_CTRL_select                                             0x1000000000000040ULL
#define GPIO_CTRL_direction                                          0x1010000000000040ULL

//
// Register:    GPIO_IOCTRL
// Description: GPIO IO Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     ds                             16  15:00 RW   0x0         IO strength setting
//     pull_en                        16  31:16 RW   0x0         Pull Enabled
//
#define GPIO_IOCTRL                                                  0x0000000000000044ULL
#define GPIO_IOCTRL_ds                                               0x1000000000000044ULL
#define GPIO_IOCTRL_pull_en                                          0x1010000000000044ULL

//
// Register:    GPIO_SYNC
// Description: GPIO Synchronizer

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     syncin                         16  15:00 RW   0x0         Synchronize input GPIOs to the System Clock
//     syncout                        16  31:16 RW   0x0         Synchronize output GPIOs to the System Clock
//
#define GPIO_SYNC                                                    0x0000000000000048ULL
#define GPIO_SYNC_syncin                                             0x1000000000000048ULL
#define GPIO_SYNC_syncout                                            0x1010000000000048ULL

//
// Register:    GPIO_VALUE
// Description: GPIO Values

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     outvalue                       16  15:00 RW   0x0         Set output value for GPIOs
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define GPIO_VALUE                                                   0x000000000000004cULL
#define GPIO_VALUE_outvalue                                          0x100000000000004cULL
#define GPIO_VALUE_reserved                                          0x101000000000004cULL

//
// Register:    GPIO_MONITOR
// Description: Monitor GPIO values

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     outvalue                       16  15:00 RO   0x0         Current GPIO output values
//     invalue                        16  31:16 RO   0x0         Current GPIO input values
//
#define GPIO_MONITOR                                                 0x0000000000000050ULL
#define GPIO_MONITOR_outvalue                                        0x1000000000000050ULL
#define GPIO_MONITOR_invalue                                         0x1010000000000050ULL

//
// Register:    OTP_CTRL
// Description: OTP Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     prog_mode                      1       0 RW   0x0         Programming Mode
//     rw_operation                   2   02:01 RW   0x0         Rd/Write
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define OTP_CTRL                                                     0x0000000000000060ULL
#define OTP_CTRL_prog_mode                                           0x0100000000000060ULL
#define OTP_CTRL_rw_operation                                        0x0201000000000060ULL
#define OTP_CTRL_reserved                                            0x1d03000000000060ULL

//
// Register:    OTP_CNTR
// Description: OTP Counters

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     wr_cycle                       14  13:00 RW   0x0         Number of cycles to hold the address/data during write wrt
//                                                               otp_clk
//     reserved1                      2   15:14 RO   0x0         Reserved
//     rd_cycle                       6   21:16 RW   0x0         Number of cycles to hold Tpor during read wrt otp_clk
//     reserved2                      2   23:22 RO   0x0         Reserved
//     test_cycle                     8   31:24 RW   0x0         Number of cycles to hold Tpor during test wrt otp_clk
//
#define OTP_CNTR                                                     0x0000000000000064ULL
#define OTP_CNTR_wr_cycle                                            0x0e00000000000064ULL
#define OTP_CNTR_reserved1                                           0x020e000000000064ULL
#define OTP_CNTR_rd_cycle                                            0x0610000000000064ULL
#define OTP_CNTR_reserved2                                           0x0216000000000064ULL
#define OTP_CNTR_test_cycle                                          0x0818000000000064ULL

//
// Register:    OTP_WRDATA
// Description: OTP Write Data

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     wr_data                        32  31:00 RW   0x0         Write Data for OTP
//
#define OTP_WRDATA                                                   0x0000000000000068ULL
#define OTP_WRDATA_wr_data                                           0x2000000000000068ULL

//
// Register:    OTP_WRSEL
// Description: OTP Write Select

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     wrsel                          1       0 RW   0x0         OTP write select
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define OTP_WRSEL                                                    0x000000000000006cULL
#define OTP_WRSEL_wrsel                                              0x010000000000006cULL
#define OTP_WRSEL_reserved                                           0x1f0100000000006cULL

//
// Register:    OTP1_DATA
// Description: OTP1 Read Data

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     data                           32  31:00 RO   0x0         Read Data for OTP1
//
#define OTP1_DATA                                                    0x0000000000000070ULL
#define OTP1_DATA_data                                               0x2000000000000070ULL

//
// Register:    OTP2_DATA
// Description: OTP2 Read Data

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     data                           32  31:00 RO   0x0         Read Data for OTP2
//
#define OTP2_DATA                                                    0x0000000000000074ULL
#define OTP2_DATA_data                                               0x2000000000000074ULL

//
// Register:    OTP_STATUS
// Description: Status

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     prog_mode_set                  1       0 RO   0x0         Programming Mode
//     write_done                     1       1 RO   0x0         Write is done
//     read_done                      1       2 RO   0x0         Read is done
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define OTP_STATUS                                                   0x0000000000000078ULL
#define OTP_STATUS_prog_mode_set                                     0x0100000000000078ULL
#define OTP_STATUS_write_done                                        0x0101000000000078ULL
#define OTP_STATUS_read_done                                         0x0102000000000078ULL
#define OTP_STATUS_reserved                                          0x1d03000000000078ULL

//
// Register:    B0_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B0_LVDSIF_CTRL                                               0x0000000000002000ULL
#define B0_LVDSIF_CTRL_lane_enable                                   0x0800000000002000ULL
#define B0_LVDSIF_CTRL_pattern_enable                                0x0808000000002000ULL
#define B0_LVDSIF_CTRL_prbs_enable                                   0x0810000000002000ULL
#define B0_LVDSIF_CTRL_reserved                                      0x0818000000002000ULL

//
// Register:    B0_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B0_RDOUT_CTRL                                                0x0000000000002004ULL
#define B0_RDOUT_CTRL_crc_enable                                     0x0100000000002004ULL
#define B0_RDOUT_CTRL_reserved                                       0x1f01000000002004ULL

//
// Register:    B0_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B0_SRDWR_PRECHARGE                                           0x0000000000002008ULL
#define B0_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002008ULL
#define B0_SRDWR_PRECHARGE_reserved                                  0x1808000000002008ULL

//
// Register:    B0_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B0_SRDWR_BANK1M_PD                                           0x000000000000200cULL
#define B0_SRDWR_BANK1M_PD_bank1m_pd                                 0x100000000000200cULL
#define B0_SRDWR_BANK1M_PD_reserved                                  0x101000000000200cULL

//
// Register:    B0_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B0_SRDWR_VLIQ_SYNC                                           0x0000000000002010ULL
#define B0_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002010ULL
#define B0_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002010ULL

//
// Register:    B0_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B0_SRDWR_STATUS0                                             0x0000000000002020ULL
#define B0_SRDWR_STATUS0_busy_rd                                     0x0100000000002020ULL
#define B0_SRDWR_STATUS0_busy_smem                                   0x0101000000002020ULL
#define B0_SRDWR_STATUS0_reserved                                    0x0e02000000002020ULL
#define B0_SRDWR_STATUS0_framecnt                                    0x1010000000002020ULL

//
// Register:    B0_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B0_SRDWR_STATUS1                                             0x0000000000002024ULL
#define B0_SRDWR_STATUS1_sframecnt                                   0x2000000000002024ULL

//
// Register:    B0_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B0_SRDWR_STATUS2                                             0x0000000000002028ULL
#define B0_SRDWR_STATUS2_rowcnt                                      0x0900000000002028ULL
#define B0_SRDWR_STATUS2_reserved                                    0x1609000000002028ULL
#define B0_SRDWR_STATUS2_dark_period                                 0x011f000000002028ULL

//
// Register:    B1_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B1_LVDSIF_CTRL                                               0x0000000000002200ULL
#define B1_LVDSIF_CTRL_lane_enable                                   0x0800000000002200ULL
#define B1_LVDSIF_CTRL_pattern_enable                                0x0808000000002200ULL
#define B1_LVDSIF_CTRL_prbs_enable                                   0x0810000000002200ULL
#define B1_LVDSIF_CTRL_reserved                                      0x0818000000002200ULL

//
// Register:    B1_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B1_RDOUT_CTRL                                                0x0000000000002204ULL
#define B1_RDOUT_CTRL_crc_enable                                     0x0100000000002204ULL
#define B1_RDOUT_CTRL_reserved                                       0x1f01000000002204ULL

//
// Register:    B1_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B1_SRDWR_PRECHARGE                                           0x0000000000002208ULL
#define B1_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002208ULL
#define B1_SRDWR_PRECHARGE_reserved                                  0x1808000000002208ULL

//
// Register:    B1_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B1_SRDWR_BANK1M_PD                                           0x000000000000220cULL
#define B1_SRDWR_BANK1M_PD_bank1m_pd                                 0x100000000000220cULL
#define B1_SRDWR_BANK1M_PD_reserved                                  0x101000000000220cULL

//
// Register:    B1_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B1_SRDWR_VLIQ_SYNC                                           0x0000000000002210ULL
#define B1_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002210ULL
#define B1_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002210ULL

//
// Register:    B1_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B1_SRDWR_STATUS0                                             0x0000000000002220ULL
#define B1_SRDWR_STATUS0_busy_rd                                     0x0100000000002220ULL
#define B1_SRDWR_STATUS0_busy_smem                                   0x0101000000002220ULL
#define B1_SRDWR_STATUS0_reserved                                    0x0e02000000002220ULL
#define B1_SRDWR_STATUS0_framecnt                                    0x1010000000002220ULL

//
// Register:    B1_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B1_SRDWR_STATUS1                                             0x0000000000002224ULL
#define B1_SRDWR_STATUS1_sframecnt                                   0x2000000000002224ULL

//
// Register:    B1_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B1_SRDWR_STATUS2                                             0x0000000000002228ULL
#define B1_SRDWR_STATUS2_rowcnt                                      0x0900000000002228ULL
#define B1_SRDWR_STATUS2_reserved                                    0x1609000000002228ULL
#define B1_SRDWR_STATUS2_dark_period                                 0x011f000000002228ULL

//
// Register:    B2_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B2_LVDSIF_CTRL                                               0x0000000000002400ULL
#define B2_LVDSIF_CTRL_lane_enable                                   0x0800000000002400ULL
#define B2_LVDSIF_CTRL_pattern_enable                                0x0808000000002400ULL
#define B2_LVDSIF_CTRL_prbs_enable                                   0x0810000000002400ULL
#define B2_LVDSIF_CTRL_reserved                                      0x0818000000002400ULL

//
// Register:    B2_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B2_RDOUT_CTRL                                                0x0000000000002404ULL
#define B2_RDOUT_CTRL_crc_enable                                     0x0100000000002404ULL
#define B2_RDOUT_CTRL_reserved                                       0x1f01000000002404ULL

//
// Register:    B2_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B2_SRDWR_PRECHARGE                                           0x0000000000002408ULL
#define B2_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002408ULL
#define B2_SRDWR_PRECHARGE_reserved                                  0x1808000000002408ULL

//
// Register:    B2_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B2_SRDWR_BANK1M_PD                                           0x000000000000240cULL
#define B2_SRDWR_BANK1M_PD_bank1m_pd                                 0x100000000000240cULL
#define B2_SRDWR_BANK1M_PD_reserved                                  0x101000000000240cULL

//
// Register:    B2_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B2_SRDWR_VLIQ_SYNC                                           0x0000000000002410ULL
#define B2_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002410ULL
#define B2_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002410ULL

//
// Register:    B2_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B2_SRDWR_STATUS0                                             0x0000000000002420ULL
#define B2_SRDWR_STATUS0_busy_rd                                     0x0100000000002420ULL
#define B2_SRDWR_STATUS0_busy_smem                                   0x0101000000002420ULL
#define B2_SRDWR_STATUS0_reserved                                    0x0e02000000002420ULL
#define B2_SRDWR_STATUS0_framecnt                                    0x1010000000002420ULL

//
// Register:    B2_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B2_SRDWR_STATUS1                                             0x0000000000002424ULL
#define B2_SRDWR_STATUS1_sframecnt                                   0x2000000000002424ULL

//
// Register:    B2_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B2_SRDWR_STATUS2                                             0x0000000000002428ULL
#define B2_SRDWR_STATUS2_rowcnt                                      0x0900000000002428ULL
#define B2_SRDWR_STATUS2_reserved                                    0x1609000000002428ULL
#define B2_SRDWR_STATUS2_dark_period                                 0x011f000000002428ULL

//
// Register:    B3_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B3_LVDSIF_CTRL                                               0x0000000000002600ULL
#define B3_LVDSIF_CTRL_lane_enable                                   0x0800000000002600ULL
#define B3_LVDSIF_CTRL_pattern_enable                                0x0808000000002600ULL
#define B3_LVDSIF_CTRL_prbs_enable                                   0x0810000000002600ULL
#define B3_LVDSIF_CTRL_reserved                                      0x0818000000002600ULL

//
// Register:    B3_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B3_RDOUT_CTRL                                                0x0000000000002604ULL
#define B3_RDOUT_CTRL_crc_enable                                     0x0100000000002604ULL
#define B3_RDOUT_CTRL_reserved                                       0x1f01000000002604ULL

//
// Register:    B3_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B3_SRDWR_PRECHARGE                                           0x0000000000002608ULL
#define B3_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002608ULL
#define B3_SRDWR_PRECHARGE_reserved                                  0x1808000000002608ULL

//
// Register:    B3_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B3_SRDWR_BANK1M_PD                                           0x000000000000260cULL
#define B3_SRDWR_BANK1M_PD_bank1m_pd                                 0x100000000000260cULL
#define B3_SRDWR_BANK1M_PD_reserved                                  0x101000000000260cULL

//
// Register:    B3_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B3_SRDWR_VLIQ_SYNC                                           0x0000000000002610ULL
#define B3_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002610ULL
#define B3_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002610ULL

//
// Register:    B3_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B3_SRDWR_STATUS0                                             0x0000000000002620ULL
#define B3_SRDWR_STATUS0_busy_rd                                     0x0100000000002620ULL
#define B3_SRDWR_STATUS0_busy_smem                                   0x0101000000002620ULL
#define B3_SRDWR_STATUS0_reserved                                    0x0e02000000002620ULL
#define B3_SRDWR_STATUS0_framecnt                                    0x1010000000002620ULL

//
// Register:    B3_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B3_SRDWR_STATUS1                                             0x0000000000002624ULL
#define B3_SRDWR_STATUS1_sframecnt                                   0x2000000000002624ULL

//
// Register:    B3_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B3_SRDWR_STATUS2                                             0x0000000000002628ULL
#define B3_SRDWR_STATUS2_rowcnt                                      0x0900000000002628ULL
#define B3_SRDWR_STATUS2_reserved                                    0x1609000000002628ULL
#define B3_SRDWR_STATUS2_dark_period                                 0x011f000000002628ULL

//
// Register:    B4_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B4_LVDSIF_CTRL                                               0x0000000000002800ULL
#define B4_LVDSIF_CTRL_lane_enable                                   0x0800000000002800ULL
#define B4_LVDSIF_CTRL_pattern_enable                                0x0808000000002800ULL
#define B4_LVDSIF_CTRL_prbs_enable                                   0x0810000000002800ULL
#define B4_LVDSIF_CTRL_reserved                                      0x0818000000002800ULL

//
// Register:    B4_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B4_RDOUT_CTRL                                                0x0000000000002804ULL
#define B4_RDOUT_CTRL_crc_enable                                     0x0100000000002804ULL
#define B4_RDOUT_CTRL_reserved                                       0x1f01000000002804ULL

//
// Register:    B4_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B4_SRDWR_PRECHARGE                                           0x0000000000002808ULL
#define B4_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002808ULL
#define B4_SRDWR_PRECHARGE_reserved                                  0x1808000000002808ULL

//
// Register:    B4_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B4_SRDWR_BANK1M_PD                                           0x000000000000280cULL
#define B4_SRDWR_BANK1M_PD_bank1m_pd                                 0x100000000000280cULL
#define B4_SRDWR_BANK1M_PD_reserved                                  0x101000000000280cULL

//
// Register:    B4_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B4_SRDWR_VLIQ_SYNC                                           0x0000000000002810ULL
#define B4_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002810ULL
#define B4_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002810ULL

//
// Register:    B4_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B4_SRDWR_STATUS0                                             0x0000000000002820ULL
#define B4_SRDWR_STATUS0_busy_rd                                     0x0100000000002820ULL
#define B4_SRDWR_STATUS0_busy_smem                                   0x0101000000002820ULL
#define B4_SRDWR_STATUS0_reserved                                    0x0e02000000002820ULL
#define B4_SRDWR_STATUS0_framecnt                                    0x1010000000002820ULL

//
// Register:    B4_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B4_SRDWR_STATUS1                                             0x0000000000002824ULL
#define B4_SRDWR_STATUS1_sframecnt                                   0x2000000000002824ULL

//
// Register:    B4_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B4_SRDWR_STATUS2                                             0x0000000000002828ULL
#define B4_SRDWR_STATUS2_rowcnt                                      0x0900000000002828ULL
#define B4_SRDWR_STATUS2_reserved                                    0x1609000000002828ULL
#define B4_SRDWR_STATUS2_dark_period                                 0x011f000000002828ULL

//
// Register:    B5_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B5_LVDSIF_CTRL                                               0x0000000000002a00ULL
#define B5_LVDSIF_CTRL_lane_enable                                   0x0800000000002a00ULL
#define B5_LVDSIF_CTRL_pattern_enable                                0x0808000000002a00ULL
#define B5_LVDSIF_CTRL_prbs_enable                                   0x0810000000002a00ULL
#define B5_LVDSIF_CTRL_reserved                                      0x0818000000002a00ULL

//
// Register:    B5_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B5_RDOUT_CTRL                                                0x0000000000002a04ULL
#define B5_RDOUT_CTRL_crc_enable                                     0x0100000000002a04ULL
#define B5_RDOUT_CTRL_reserved                                       0x1f01000000002a04ULL

//
// Register:    B5_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B5_SRDWR_PRECHARGE                                           0x0000000000002a08ULL
#define B5_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002a08ULL
#define B5_SRDWR_PRECHARGE_reserved                                  0x1808000000002a08ULL

//
// Register:    B5_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B5_SRDWR_BANK1M_PD                                           0x0000000000002a0cULL
#define B5_SRDWR_BANK1M_PD_bank1m_pd                                 0x1000000000002a0cULL
#define B5_SRDWR_BANK1M_PD_reserved                                  0x1010000000002a0cULL

//
// Register:    B5_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B5_SRDWR_VLIQ_SYNC                                           0x0000000000002a10ULL
#define B5_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002a10ULL
#define B5_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002a10ULL

//
// Register:    B5_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B5_SRDWR_STATUS0                                             0x0000000000002a20ULL
#define B5_SRDWR_STATUS0_busy_rd                                     0x0100000000002a20ULL
#define B5_SRDWR_STATUS0_busy_smem                                   0x0101000000002a20ULL
#define B5_SRDWR_STATUS0_reserved                                    0x0e02000000002a20ULL
#define B5_SRDWR_STATUS0_framecnt                                    0x1010000000002a20ULL

//
// Register:    B5_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B5_SRDWR_STATUS1                                             0x0000000000002a24ULL
#define B5_SRDWR_STATUS1_sframecnt                                   0x2000000000002a24ULL

//
// Register:    B5_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B5_SRDWR_STATUS2                                             0x0000000000002a28ULL
#define B5_SRDWR_STATUS2_rowcnt                                      0x0900000000002a28ULL
#define B5_SRDWR_STATUS2_reserved                                    0x1609000000002a28ULL
#define B5_SRDWR_STATUS2_dark_period                                 0x011f000000002a28ULL

//
// Register:    B6_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B6_LVDSIF_CTRL                                               0x0000000000002c00ULL
#define B6_LVDSIF_CTRL_lane_enable                                   0x0800000000002c00ULL
#define B6_LVDSIF_CTRL_pattern_enable                                0x0808000000002c00ULL
#define B6_LVDSIF_CTRL_prbs_enable                                   0x0810000000002c00ULL
#define B6_LVDSIF_CTRL_reserved                                      0x0818000000002c00ULL

//
// Register:    B6_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B6_RDOUT_CTRL                                                0x0000000000002c04ULL
#define B6_RDOUT_CTRL_crc_enable                                     0x0100000000002c04ULL
#define B6_RDOUT_CTRL_reserved                                       0x1f01000000002c04ULL

//
// Register:    B6_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B6_SRDWR_PRECHARGE                                           0x0000000000002c08ULL
#define B6_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002c08ULL
#define B6_SRDWR_PRECHARGE_reserved                                  0x1808000000002c08ULL

//
// Register:    B6_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B6_SRDWR_BANK1M_PD                                           0x0000000000002c0cULL
#define B6_SRDWR_BANK1M_PD_bank1m_pd                                 0x1000000000002c0cULL
#define B6_SRDWR_BANK1M_PD_reserved                                  0x1010000000002c0cULL

//
// Register:    B6_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B6_SRDWR_VLIQ_SYNC                                           0x0000000000002c10ULL
#define B6_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002c10ULL
#define B6_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002c10ULL

//
// Register:    B6_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B6_SRDWR_STATUS0                                             0x0000000000002c20ULL
#define B6_SRDWR_STATUS0_busy_rd                                     0x0100000000002c20ULL
#define B6_SRDWR_STATUS0_busy_smem                                   0x0101000000002c20ULL
#define B6_SRDWR_STATUS0_reserved                                    0x0e02000000002c20ULL
#define B6_SRDWR_STATUS0_framecnt                                    0x1010000000002c20ULL

//
// Register:    B6_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B6_SRDWR_STATUS1                                             0x0000000000002c24ULL
#define B6_SRDWR_STATUS1_sframecnt                                   0x2000000000002c24ULL

//
// Register:    B6_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B6_SRDWR_STATUS2                                             0x0000000000002c28ULL
#define B6_SRDWR_STATUS2_rowcnt                                      0x0900000000002c28ULL
#define B6_SRDWR_STATUS2_reserved                                    0x1609000000002c28ULL
#define B6_SRDWR_STATUS2_dark_period                                 0x011f000000002c28ULL

//
// Register:    B7_LVDSIF_CTRL
// Description: LVDS Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     lane_enable                    8   07:00 RW   0x0         One enable bit per lane
//     pattern_enable                 8   15:08 RW   0x0         One enable bit per lane
//     prbs_enable                    8   23:16 RW   0x0         One enable bit per lane
//     reserved                       8   31:24 RO   0x0         Reserved
//
#define B7_LVDSIF_CTRL                                               0x0000000000002e00ULL
#define B7_LVDSIF_CTRL_lane_enable                                   0x0800000000002e00ULL
#define B7_LVDSIF_CTRL_pattern_enable                                0x0808000000002e00ULL
#define B7_LVDSIF_CTRL_prbs_enable                                   0x0810000000002e00ULL
#define B7_LVDSIF_CTRL_reserved                                      0x0818000000002e00ULL

//
// Register:    B7_RDOUT_CTRL
// Description: Read-Out Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     crc_enable                     1       0 RW   0x0         Enable CRC footer
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define B7_RDOUT_CTRL                                                0x0000000000002e04ULL
#define B7_RDOUT_CTRL_crc_enable                                     0x0100000000002e04ULL
#define B7_RDOUT_CTRL_reserved                                       0x1f01000000002e04ULL

//
// Register:    B7_SRDWR_PRECHARGE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge64rows                8   07:00 RW   0x0         Precharge selected rows
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define B7_SRDWR_PRECHARGE                                           0x0000000000002e08ULL
#define B7_SRDWR_PRECHARGE_precharge64rows                           0x0800000000002e08ULL
#define B7_SRDWR_PRECHARGE_reserved                                  0x1808000000002e08ULL

//
// Register:    B7_SRDWR_BANK1M_PD
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     bank1m_pd                      16  15:00 RW   0x0         This field connects to bank1m array's pd[15:0] input
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B7_SRDWR_BANK1M_PD                                           0x0000000000002e0cULL
#define B7_SRDWR_BANK1M_PD_bank1m_pd                                 0x1000000000002e0cULL
#define B7_SRDWR_BANK1M_PD_reserved                                  0x1010000000002e0cULL

//
// Register:    B7_SRDWR_VLIQ_SYNC
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_sync_dly                  3   02:00 RW   0x0         Hardware synchronization delay
//     reserved                       29  31:03 RO   0x0         Reserved
//
#define B7_SRDWR_VLIQ_SYNC                                           0x0000000000002e10ULL
#define B7_SRDWR_VLIQ_SYNC_vliq_sync_dly                             0x0300000000002e10ULL
#define B7_SRDWR_VLIQ_SYNC_reserved                                  0x1d03000000002e10ULL

//
// Register:    B7_SRDWR_STATUS0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     busy_rd                        1       0 RO   0x0         busy reading sensor data
//     busy_smem                      1       1 RO   0x0         busy accessing SMEM
//     reserved                       14  15:02 RO   0x0         Reserved
//     framecnt                       16  31:16 RO   0x0         Frame count, resets at rising and falling edges of Vliq
//
#define B7_SRDWR_STATUS0                                             0x0000000000002e20ULL
#define B7_SRDWR_STATUS0_busy_rd                                     0x0100000000002e20ULL
#define B7_SRDWR_STATUS0_busy_smem                                   0x0101000000002e20ULL
#define B7_SRDWR_STATUS0_reserved                                    0x0e02000000002e20ULL
#define B7_SRDWR_STATUS0_framecnt                                    0x1010000000002e20ULL

//
// Register:    B7_SRDWR_STATUS1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframecnt                      32  31:00 RO   0x0         Super Frame Count
//
#define B7_SRDWR_STATUS1                                             0x0000000000002e24ULL
#define B7_SRDWR_STATUS1_sframecnt                                   0x2000000000002e24ULL

//
// Register:    B7_SRDWR_STATUS2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rowcnt                         9   08:00 RO   0x0         Current Row Count
//     reserved                       22  30:09 RO   0x0         Reserved
//     dark_period                    1      31 RO   0x0         0 = bright
//
#define B7_SRDWR_STATUS2                                             0x0000000000002e28ULL
#define B7_SRDWR_STATUS2_rowcnt                                      0x0900000000002e28ULL
#define B7_SRDWR_STATUS2_reserved                                    0x1609000000002e28ULL
#define B7_SRDWR_STATUS2_dark_period                                 0x011f000000002e28ULL

//
// Register:    LVDSIF_PATTERN
// Description: LVDS Patterns

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pattern0                       8   07:00 RW   0x0         Pattern 0 and PRBS seed
//     pattern1                       8   15:08 RW   0x0         Pattern 1
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define LVDSIF_PATTERN                                               0x0000000000004000ULL
#define LVDSIF_PATTERN_pattern0                                      0x0800000000004000ULL
#define LVDSIF_PATTERN_pattern1                                      0x0808000000004000ULL
#define LVDSIF_PATTERN_reserved                                      0x1010000000004000ULL

//
// Register:    LVDSIF_IOCTRL
// Description: LVDS IO Control

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     data_cm                        2   01:00 RW   0x0         LVDS Data IO Common Mode setting
//     bias_sel                       2   03:02 RW   0x0         LVDS Data IO Output BIAS current adjustment
//     lvds0_mon                      2   05:04 RW   0x0         Clock Monitoring for the LVDS0 Bank
//     reserved1                      2   07:06 RO   0x0         Reserved
//     data_pd                        8   15:08 RW   0x0         One pd bit per bank (8 lanes)
//     reserved2                      16  31:16 RO   0x0         Reserved
//
#define LVDSIF_IOCTRL                                                0x0000000000004004ULL
#define LVDSIF_IOCTRL_data_cm                                        0x0200000000004004ULL
#define LVDSIF_IOCTRL_bias_sel                                       0x0202000000004004ULL
#define LVDSIF_IOCTRL_lvds0_mon                                      0x0204000000004004ULL
#define LVDSIF_IOCTRL_reserved1                                      0x0206000000004004ULL
#define LVDSIF_IOCTRL_data_pd                                        0x0808000000004004ULL
#define LVDSIF_IOCTRL_reserved2                                      0x1010000000004004ULL

//
// Register:    SRDWR_READ_ENABLE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     read_en                        1       0 RW   0x0         Set to start reads, reset to stop
//     reserved                       31  31:01 RO   0x0         Reserved
//
#define SRDWR_READ_ENABLE                                            0x0000000000004020ULL
#define SRDWR_READ_ENABLE_read_en                                    0x0100000000004020ULL
#define SRDWR_READ_ENABLE_reserved                                   0x1f01000000004020ULL

//
// Register:    SRDWR_READ_CONTROL0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     skip_row                       1       0 RW   0x0         Skip all odd # rows
//     vliq_ext                       1       1 RW   0x0         If set, dark/bright signal is an input instead of internally
//                                                               generated
//     reserved1                      6   07:02 RO   0x0         Reserved
//     adc_capture_dly                5   12:08 RW   0x0         ADC output intial capture delay
//     reserved2                      3   15:13 RO   0x0         Reserved
//     int_time                       11  26:16 RW   0x0         Add Integration time (in # of frames) after a frame has been
//                                                               read
//     reserved3                      1      27 RO   0x0         Reserved
//     rowsel_ser_en                  1      28 RW   0x0         rowsel serial load enable
//     precharge_ser_en               1      29 RW   0x0         precharge serial load enable
//     header_dis                     1      30 RW   0x0         If set, will disable header and footer insertion in sensor
//                                                               frame readout data
//     stream_mode                    1      31 RW   0x0         If set, sensor data is streamed until read_en is reset
//
#define SRDWR_READ_CONTROL0                                          0x0000000000004024ULL
#define SRDWR_READ_CONTROL0_skip_row                                 0x0100000000004024ULL
#define SRDWR_READ_CONTROL0_vliq_ext                                 0x0101000000004024ULL
#define SRDWR_READ_CONTROL0_reserved1                                0x0602000000004024ULL
#define SRDWR_READ_CONTROL0_adc_capture_dly                          0x0508000000004024ULL
#define SRDWR_READ_CONTROL0_reserved2                                0x030d000000004024ULL
#define SRDWR_READ_CONTROL0_int_time                                 0x0b10000000004024ULL
#define SRDWR_READ_CONTROL0_reserved3                                0x011b000000004024ULL
#define SRDWR_READ_CONTROL0_rowsel_ser_en                            0x011c000000004024ULL
#define SRDWR_READ_CONTROL0_precharge_ser_en                         0x011d000000004024ULL
#define SRDWR_READ_CONTROL0_header_dis                               0x011e000000004024ULL
#define SRDWR_READ_CONTROL0_stream_mode                              0x011f000000004024ULL

//
// Register:    SRDWR_READ_CONTROL1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     sframe_num                     32  31:00 RW   0x0         Superframe number
//
#define SRDWR_READ_CONTROL1                                          0x0000000000004028ULL
#define SRDWR_READ_CONTROL1_sframe_num                               0x2000000000004028ULL

//
// Register:    SRDWR_SMEM_CONTROL
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     smem_dis_all                   1       0 RW   0x0         Set this bit to disable all cells in bank1m, HW clears this
//                                                               bit when done, busy will be asserted
//     smem_en_all                    1       1 RW   0x0         Set this bit to enable all cells in bank1m, HW clears this
//                                                               bit when done, busy will be asserted
//     reserved                       30  31:02 RO   0x0         Reserved
//
#define SRDWR_SMEM_CONTROL                                           0x000000000000402cULL
#define SRDWR_SMEM_CONTROL_smem_dis_all                              0x010000000000402cULL
#define SRDWR_SMEM_CONTROL_smem_en_all                               0x010100000000402cULL
#define SRDWR_SMEM_CONTROL_reserved                                  0x1e0200000000402cULL

//
// Register:    SRDWR_RECHARGE_START
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rcharge_dk_start               14  13:00 RW   0x0         Recharge bright start (in row time, 0 to 1ms in 2us
//                                                               increments), only applies if rcharge_br_time is not 0
//     reserved1                      2   15:14 RO   0x0         Reserved
//     rcharge_bk_start               14  29:16 RW   0x0         Recharge dark start (in row time, 0 to 1ms in 2us
//                                                               increments), only applies if rcharge_dk_time is not 0
//     reserved2                      1      30 RO   0x0         Reserved
//     integrate_instd                1      31 RW   0x0         Integrate instead of recharge
//
#define SRDWR_RECHARGE_START                                         0x0000000000004030ULL
#define SRDWR_RECHARGE_START_rcharge_dk_start                        0x0e00000000004030ULL
#define SRDWR_RECHARGE_START_reserved1                               0x020e000000004030ULL
#define SRDWR_RECHARGE_START_rcharge_bk_start                        0x0e10000000004030ULL
#define SRDWR_RECHARGE_START_reserved2                               0x011e000000004030ULL
#define SRDWR_RECHARGE_START_integrate_instd                         0x011f000000004030ULL

//
// Register:    SRDWR_RECHARGE_TIME
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     rcharge_dk_time                14  13:00 RW   0x0         Recharge period during bright period in row time, 12 bit =
//                                                               4096 for up to 8 frames, set to 0 to disable
//     reserved1                      2   15:14 RO   0x0         Reserved
//     rcharge_bk_time                14  29:16 RW   0x0         Recharge period during dark period in row time 12 bit = 4096
//                                                               for up to 8 frames, set to 0 to disable
//     reserved2                      2   31:30 RO   0x0         Reserved
//
#define SRDWR_RECHARGE_TIME                                          0x0000000000004034ULL
#define SRDWR_RECHARGE_TIME_rcharge_dk_time                          0x0e00000000004034ULL
#define SRDWR_RECHARGE_TIME_reserved1                                0x020e000000004034ULL
#define SRDWR_RECHARGE_TIME_rcharge_bk_time                          0x0e10000000004034ULL
#define SRDWR_RECHARGE_TIME_reserved2                                0x021e000000004034ULL

//
// Register:    SRDWR_BANK1M_CONTROL
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     conv_en_posedge                8   07:00 RW   0x0         conv_en generated on positive edge of clk
//     dis_ncap                       1       8 RW   0x0         disconnect ncap
//     selvpre2_en                    1       9 RW   0x0         enable software control selvpre2
//     selvpre2_val                   1      10 RW   0x0         selvpre2 value if selvpre2_en is set
//     reserved                       21  31:11 RO   0x0         Reserved
//
#define SRDWR_BANK1M_CONTROL                                         0x0000000000004038ULL
#define SRDWR_BANK1M_CONTROL_conv_en_posedge                         0x0800000000004038ULL
#define SRDWR_BANK1M_CONTROL_dis_ncap                                0x0108000000004038ULL
#define SRDWR_BANK1M_CONTROL_selvpre2_en                             0x0109000000004038ULL
#define SRDWR_BANK1M_CONTROL_selvpre2_val                            0x010a000000004038ULL
#define SRDWR_BANK1M_CONTROL_reserved                                0x150b000000004038ULL

//
// Register:    SRDWR_VLIQ_PERIOD
// Description: Frame Period

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     br_period                      16  15:00 RW   0x0         Bright period in frames
//     dk_period                      16  31:16 RW   0x0         Dark Period in frames
//
#define SRDWR_VLIQ_PERIOD                                            0x0000000000004040ULL
#define SRDWR_VLIQ_PERIOD_br_period                                  0x1000000000004040ULL
#define SRDWR_VLIQ_PERIOD_dk_period                                  0x1010000000004040ULL

//
// Register:    SRDWR_VLIQ_PHASE_CTL
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     br_phase                       10  09:00 RW   0x0         Add # of row time of delay after rising edge of bright
//                                                               period
//     br_phase_cnt                   6   15:10 RW   0x0         Number of super frames to apply br_phase_delay
//     dk_phase                       10  25:16 RW   0x0         Add # or row time of delay after rising edge of dark period
//     dk_phase_cnt                   6   31:26 RW   0x0         Number of super frames to apply dk_phase_delay
//
#define SRDWR_VLIQ_PHASE_CTL                                         0x0000000000004044ULL
#define SRDWR_VLIQ_PHASE_CTL_br_phase                                0x0a00000000004044ULL
#define SRDWR_VLIQ_PHASE_CTL_br_phase_cnt                            0x060a000000004044ULL
#define SRDWR_VLIQ_PHASE_CTL_dk_phase                                0x0a10000000004044ULL
#define SRDWR_VLIQ_PHASE_CTL_dk_phase_cnt                            0x061a000000004044ULL

//
// Register:    SRDWR_VLIQ_DELAY
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     vliq_delay                     8   07:00 RW   0x0         Phase delay (in row time) between Vliq (internally generated
//                                                               or external) and Vliq input to rd/wr control
//     reserved                       12  19:08 RO   0x0         Reserved
//     dbg_rowsel_hld_sel             2   21:20 RW   0x0         Freeze rowsel:
//     dbg_colsel_pat_en              1      22 RW   0x0         debug colsel pattern enable
//     dbg_rowsel_hld_en              1      23 RW   0x0         debug rowsel hold enable
//     dbg_colsel_pat                 8   31:24 RW   0x0         debug colsel pattern
//
#define SRDWR_VLIQ_DELAY                                             0x0000000000004048ULL
#define SRDWR_VLIQ_DELAY_vliq_delay                                  0x0800000000004048ULL
#define SRDWR_VLIQ_DELAY_reserved                                    0x0c08000000004048ULL
#define SRDWR_VLIQ_DELAY_dbg_rowsel_hld_sel                          0x0214000000004048ULL
#define SRDWR_VLIQ_DELAY_dbg_colsel_pat_en                           0x0116000000004048ULL
#define SRDWR_VLIQ_DELAY_dbg_rowsel_hld_en                           0x0117000000004048ULL
#define SRDWR_VLIQ_DELAY_dbg_colsel_pat                              0x0818000000004048ULL

//
// Register:    SRDWR_DARK_FRAME
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     dk_frame_end                   16  15:00 RW   0x0         Dark Frame End
//     dk_frame_start                 16  31:16 RW   0x0         Dark Frame Start
//
#define SRDWR_DARK_FRAME                                             0x000000000000404cULL
#define SRDWR_DARK_FRAME_dk_frame_end                                0x100000000000404cULL
#define SRDWR_DARK_FRAME_dk_frame_start                              0x101000000000404cULL

//
// Register:    SRDWR_BRIGHT_FRAME
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     br_frame_end                   16  15:00 RW   0x0         Bright Frame End
//     br_frame_start                 16  31:16 RW   0x0         Bright Frame Start
//
#define SRDWR_BRIGHT_FRAME                                           0x0000000000004050ULL
#define SRDWR_BRIGHT_FRAME_br_frame_end                              0x1000000000004050ULL
#define SRDWR_BRIGHT_FRAME_br_frame_start                            0x1010000000004050ULL

//
// Register:    SRDWR_FRAME_WINDOW
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     frame_end                      9   08:00 RW   0x0         Frame row End
//     reserved1                      7   15:09 RO   0x0         Reserved
//     frame_start                    9   24:16 RW   0x0         Frame Row Start
//     reserved2                      7   31:25 RO   0x0         Reserved
//
#define SRDWR_FRAME_WINDOW                                           0x0000000000004054ULL
#define SRDWR_FRAME_WINDOW_frame_end                                 0x0900000000004054ULL
#define SRDWR_FRAME_WINDOW_reserved1                                 0x0709000000004054ULL
#define SRDWR_FRAME_WINDOW_frame_start                               0x0910000000004054ULL
#define SRDWR_FRAME_WINDOW_reserved2                                 0x0719000000004054ULL

//
// Register:    SRDWR_CGAIN_BRIGHT
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     cgain_bright                   32  31:00 RW   0x0         Bright period cgain frame pattern, bit 0 of this pattern is
//                                                               connected to cgain input port on bank1m
//
#define SRDWR_CGAIN_BRIGHT                                           0x0000000000004058ULL
#define SRDWR_CGAIN_BRIGHT_cgain_bright                              0x2000000000004058ULL

//
// Register:    SRDWR_CGAIN_DARK
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     cgain_dark                     32  31:00 RW   0x0         Dark period cgain frame pattern, bit 0 of this pattern is
//                                                               connected to cgain input port on bank1m
//
#define SRDWR_CGAIN_DARK                                             0x000000000000405cULL
#define SRDWR_CGAIN_DARK_cgain_dark                                  0x200000000000405cULL

//
// Register:    SRDWR_VERSION
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     version                        32  31:00 RW   0x0         This value is added to every frame header
//
#define SRDWR_VERSION                                                0x0000000000004060ULL
#define SRDWR_VERSION_version                                        0x2000000000004060ULL

//
// Register:    SRDWR_HEADER_PATTERN
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     header_pat                     32  31:00 RW   0x0         This field is used in header for sensor  readout, it can be
//                                                               programmed to have IC2 compatible sync pattern
//
#define SRDWR_HEADER_PATTERN                                         0x0000000000004064ULL
#define SRDWR_HEADER_PATTERN_header_pat                              0x2000000000004064ULL

//
// Register:    SRDWR_WEEP_CONTROL
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     weep_control                   32  31:00 RW   0x0
//
#define SRDWR_WEEP_CONTROL                                           0x0000000000004068ULL
#define SRDWR_WEEP_CONTROL_weep_control                              0x2000000000004068ULL

//
// Register:    SRDWR_WEEP_DATA
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     weep_data                      32  31:00 RO   0x0
//
#define SRDWR_WEEP_DATA                                              0x000000000000406cULL
#define SRDWR_WEEP_DATA_weep_data                                    0x200000000000406cULL

//
// Register:    SRDWR_PA_MODE
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_mode                        1       0 RW   0x0         Enable Phase Array mode
//     reserved                       3   03:01 RO   0x0         Reserved
//     pre_num                        5   08:04 RW   0x0         Number of precharge pulses
//     sa_mode                        1       9 RW   0x0         SA mode
//     src_sel                        2   11:10 RW   0x0         pa signal source select
//     frame_num                      4   15:12 RW   0x0         number of frames
//     bot_dly                        16  31:16 RW   0x0         top to bot signal delay
//
#define SRDWR_PA_MODE                                                0x0000000000004070ULL
#define SRDWR_PA_MODE_pa_mode                                        0x0100000000004070ULL
#define SRDWR_PA_MODE_reserved                                       0x0301000000004070ULL
#define SRDWR_PA_MODE_pre_num                                        0x0504000000004070ULL
#define SRDWR_PA_MODE_sa_mode                                        0x0109000000004070ULL
#define SRDWR_PA_MODE_src_sel                                        0x020a000000004070ULL
#define SRDWR_PA_MODE_frame_num                                      0x040c000000004070ULL
#define SRDWR_PA_MODE_bot_dly                                        0x1010000000004070ULL

//
// Register:    SRDWR_PRECHARGE_CONTROL
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     dis_precharge                  8   07:00 RW   0x0         Disable precharge for each bank:
//     reserved                       24  31:08 RO   0x0         Reserved
//
#define SRDWR_PRECHARGE_CONTROL                                      0x0000000000004074ULL
#define SRDWR_PRECHARGE_CONTROL_dis_precharge                        0x0800000000004074ULL
#define SRDWR_PRECHARGE_CONTROL_reserved                             0x1808000000004074ULL

//
// Register:    SRDWR_PRECHARGE_0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_0                                            0x0000000000004080ULL
#define SRDWR_PRECHARGE_0_precharge                                  0x2000000000004080ULL

//
// Register:    SRDWR_PRECHARGE_1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_1                                            0x0000000000004084ULL
#define SRDWR_PRECHARGE_1_precharge                                  0x2000000000004084ULL

//
// Register:    SRDWR_PRECHARGE_2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_2                                            0x0000000000004088ULL
#define SRDWR_PRECHARGE_2_precharge                                  0x2000000000004088ULL

//
// Register:    SRDWR_PRECHARGE_3
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_3                                            0x000000000000408cULL
#define SRDWR_PRECHARGE_3_precharge                                  0x200000000000408cULL

//
// Register:    SRDWR_PRECHARGE_4
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_4                                            0x0000000000004090ULL
#define SRDWR_PRECHARGE_4_precharge                                  0x2000000000004090ULL

//
// Register:    SRDWR_PRECHARGE_5
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_5                                            0x0000000000004094ULL
#define SRDWR_PRECHARGE_5_precharge                                  0x2000000000004094ULL

//
// Register:    SRDWR_PRECHARGE_6
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_6                                            0x0000000000004098ULL
#define SRDWR_PRECHARGE_6_precharge                                  0x2000000000004098ULL

//
// Register:    SRDWR_PRECHARGE_7
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_7                                            0x000000000000409cULL
#define SRDWR_PRECHARGE_7_precharge                                  0x200000000000409cULL

//
// Register:    SRDWR_PRECHARGE_8
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_8                                            0x00000000000040a0ULL
#define SRDWR_PRECHARGE_8_precharge                                  0x20000000000040a0ULL

//
// Register:    SRDWR_PRECHARGE_9
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_9                                            0x00000000000040a4ULL
#define SRDWR_PRECHARGE_9_precharge                                  0x20000000000040a4ULL

//
// Register:    SRDWR_PRECHARGE_10
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_10                                           0x00000000000040a8ULL
#define SRDWR_PRECHARGE_10_precharge                                 0x20000000000040a8ULL

//
// Register:    SRDWR_PRECHARGE_11
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_11                                           0x00000000000040acULL
#define SRDWR_PRECHARGE_11_precharge                                 0x20000000000040acULL

//
// Register:    SRDWR_PRECHARGE_12
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_12                                           0x00000000000040b0ULL
#define SRDWR_PRECHARGE_12_precharge                                 0x20000000000040b0ULL

//
// Register:    SRDWR_PRECHARGE_13
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_13                                           0x00000000000040b4ULL
#define SRDWR_PRECHARGE_13_precharge                                 0x20000000000040b4ULL

//
// Register:    SRDWR_PRECHARGE_14
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_14                                           0x00000000000040b8ULL
#define SRDWR_PRECHARGE_14_precharge                                 0x20000000000040b8ULL

//
// Register:    SRDWR_PRECHARGE_15
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     precharge                      32  31:00 RW   0x0
//
#define SRDWR_PRECHARGE_15                                           0x00000000000040bcULL
#define SRDWR_PRECHARGE_15_precharge                                 0x20000000000040bcULL

//
// Register:    SRDWR_PA_PC_0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_0                                                0x00000000000040c0ULL
#define SRDWR_PA_PC_0_pa_pc                                          0x20000000000040c0ULL

//
// Register:    SRDWR_PA_PC_1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_1                                                0x00000000000040c4ULL
#define SRDWR_PA_PC_1_pa_pc                                          0x20000000000040c4ULL

//
// Register:    SRDWR_PA_PC_2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_2                                                0x00000000000040c8ULL
#define SRDWR_PA_PC_2_pa_pc                                          0x20000000000040c8ULL

//
// Register:    SRDWR_PA_PC_3
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_3                                                0x00000000000040ccULL
#define SRDWR_PA_PC_3_pa_pc                                          0x20000000000040ccULL

//
// Register:    SRDWR_PA_PC_4
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_4                                                0x00000000000040d0ULL
#define SRDWR_PA_PC_4_pa_pc                                          0x20000000000040d0ULL

//
// Register:    SRDWR_PA_PC_5
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_5                                                0x00000000000040d4ULL
#define SRDWR_PA_PC_5_pa_pc                                          0x20000000000040d4ULL

//
// Register:    SRDWR_PA_PC_6
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_6                                                0x00000000000040d8ULL
#define SRDWR_PA_PC_6_pa_pc                                          0x20000000000040d8ULL

//
// Register:    SRDWR_PA_PC_7
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_pc                          32  31:00 RW   0x0
//
#define SRDWR_PA_PC_7                                                0x00000000000040dcULL
#define SRDWR_PA_PC_7_pa_pc                                          0x20000000000040dcULL

//
// Register:    SRDWR_PA_ROW_0
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_0                                               0x00000000000040e0ULL
#define SRDWR_PA_ROW_0_pa_row                                        0x20000000000040e0ULL

//
// Register:    SRDWR_PA_ROW_1
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_1                                               0x00000000000040e4ULL
#define SRDWR_PA_ROW_1_pa_row                                        0x20000000000040e4ULL

//
// Register:    SRDWR_PA_ROW_2
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_2                                               0x00000000000040e8ULL
#define SRDWR_PA_ROW_2_pa_row                                        0x20000000000040e8ULL

//
// Register:    SRDWR_PA_ROW_3
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_3                                               0x00000000000040ecULL
#define SRDWR_PA_ROW_3_pa_row                                        0x20000000000040ecULL

//
// Register:    SRDWR_PA_ROW_4
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_4                                               0x00000000000040f0ULL
#define SRDWR_PA_ROW_4_pa_row                                        0x20000000000040f0ULL

//
// Register:    SRDWR_PA_ROW_5
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_5                                               0x00000000000040f4ULL
#define SRDWR_PA_ROW_5_pa_row                                        0x20000000000040f4ULL

//
// Register:    SRDWR_PA_ROW_6
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_6                                               0x00000000000040f8ULL
#define SRDWR_PA_ROW_6_pa_row                                        0x20000000000040f8ULL

//
// Register:    SRDWR_PA_ROW_7
// Description:

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pa_row                         32  31:00 RW   0x0
//
#define SRDWR_PA_ROW_7                                               0x00000000000040fcULL
#define SRDWR_PA_ROW_7_pa_row                                        0x20000000000040fcULL

//
// Register:    DBG_BUS_CTRL
// Description: Chip Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     enable                         24  23:00 RW   0x0         Enable Debug Module on-chip:
//     reserved                       2   25:24 RO   0x0         Reserved
//     cell_sel                       2   27:26 RW   0x0         Debug bus adc output cell select
//     select                         4   31:28 RW   0x0         Select signals:
//
#define DBG_BUS_CTRL                                                 0x0000000010000000ULL
#define DBG_BUS_CTRL_enable                                          0x1800000010000000ULL
#define DBG_BUS_CTRL_reserved                                        0x0218000010000000ULL
#define DBG_BUS_CTRL_cell_sel                                        0x021a000010000000ULL
#define DBG_BUS_CTRL_select                                          0x041c000010000000ULL

//
// Register:    DBG_SPARE
// Description: Spare Register

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     spare                          32  31:00 RW   0x0         Spare Register
//
#define DBG_SPARE                                                    0x0000000010000004ULL
#define DBG_SPARE_spare                                              0x2000000010000004ULL

//
// Register:    B0_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B0_DBG_ABUS_CTRL                                             0x0000000010000020ULL
#define B0_DBG_ABUS_CTRL_select_p                                    0x0800000010000020ULL
#define B0_DBG_ABUS_CTRL_select_n                                    0x0808000010000020ULL
#define B0_DBG_ABUS_CTRL_reserved                                    0x1010000010000020ULL

//
// Register:    B1_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B1_DBG_ABUS_CTRL                                             0x0000000010000024ULL
#define B1_DBG_ABUS_CTRL_select_p                                    0x0800000010000024ULL
#define B1_DBG_ABUS_CTRL_select_n                                    0x0808000010000024ULL
#define B1_DBG_ABUS_CTRL_reserved                                    0x1010000010000024ULL

//
// Register:    B2_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B2_DBG_ABUS_CTRL                                             0x0000000010000028ULL
#define B2_DBG_ABUS_CTRL_select_p                                    0x0800000010000028ULL
#define B2_DBG_ABUS_CTRL_select_n                                    0x0808000010000028ULL
#define B2_DBG_ABUS_CTRL_reserved                                    0x1010000010000028ULL

//
// Register:    B3_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B3_DBG_ABUS_CTRL                                             0x000000001000002cULL
#define B3_DBG_ABUS_CTRL_select_p                                    0x080000001000002cULL
#define B3_DBG_ABUS_CTRL_select_n                                    0x080800001000002cULL
#define B3_DBG_ABUS_CTRL_reserved                                    0x101000001000002cULL

//
// Register:    B4_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B4_DBG_ABUS_CTRL                                             0x0000000010000030ULL
#define B4_DBG_ABUS_CTRL_select_p                                    0x0800000010000030ULL
#define B4_DBG_ABUS_CTRL_select_n                                    0x0808000010000030ULL
#define B4_DBG_ABUS_CTRL_reserved                                    0x1010000010000030ULL

//
// Register:    B5_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B5_DBG_ABUS_CTRL                                             0x0000000010000034ULL
#define B5_DBG_ABUS_CTRL_select_p                                    0x0800000010000034ULL
#define B5_DBG_ABUS_CTRL_select_n                                    0x0808000010000034ULL
#define B5_DBG_ABUS_CTRL_reserved                                    0x1010000010000034ULL

//
// Register:    B6_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B6_DBG_ABUS_CTRL                                             0x0000000010000038ULL
#define B6_DBG_ABUS_CTRL_select_p                                    0x0800000010000038ULL
#define B6_DBG_ABUS_CTRL_select_n                                    0x0808000010000038ULL
#define B6_DBG_ABUS_CTRL_reserved                                    0x1010000010000038ULL

//
// Register:    B7_DBG_ABUS_CTRL
// Description: Chip Analog Debug Bus

// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     select_p                       8   07:00 RW   0x0         Select Analog Debug Bus signal
//     select_n                       8   15:08 RW   0x0         Select Analog Debug Bus signal, for differential output
//     reserved                       16  31:16 RO   0x0         Reserved
//
#define B7_DBG_ABUS_CTRL                                             0x000000001000003cULL
#define B7_DBG_ABUS_CTRL_select_p                                    0x080000001000003cULL
#define B7_DBG_ABUS_CTRL_select_n                                    0x080800001000003cULL
#define B7_DBG_ABUS_CTRL_reserved                                    0x101000001000003cULL


#endif /* _B0_CHIP_REG_H */

