//=====================================================
// This file was auto-generated by xlate_vreg v1.3
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    REG_LOAD_ABM_VIA_PCI
// Size:        32-bits
// Type:        Write only
// Description: Copy an ABM from host-RAM into one or both ABM buffers
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     load_0                         1       0 WO   n/a         Copy ABM from host RAM to ABM buffer #0
//     load_1                         1       1 WO   n/a         Copy ABM from host RAM to ABM buffer #1
//
#define REG_LOAD_ABM_VIA_PCI                                         0x00000000a4001000ULL
#define REG_LOAD_ABM_VIA_PCI_load_0                                  0x01000000a4001000ULL
#define REG_LOAD_ABM_VIA_PCI_load_1                                  0x01010000a4001000ULL


//
// Register:    REG_ABM_HOST_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: Source address in host RAM for loading ABMs
//
#define REG_ABM_HOST_ADDR                                            0x40000000a4001004ULL


//
// Register:    REG_SELECT_HSI
// Size:        32-bits
// Type:        Read/Write
// Description: Select HSI or SPI bus for SMEM writes
//              0 = SPI, 1 = HSI
//
#define REG_SELECT_HSI                                               0x00000000a400100cULL


//
// Register:    REG_FORCE_SMEM
// Size:        32-bits
// Type:        Read/Write
// Description: Write a 1 to force all rows of the next received ABM
//              to be written to cache and SMEM.
//              Auto-clears to 0.
//
#define REG_FORCE_SMEM                                               0x00000000a4001010ULL


//
// Register:    REG_CHIPIO_ADDR
// Size:        32-bits
// Type:        Read/Write
// Description: The address on the sensor chip that you wish to read or write
//
#define REG_CHIPIO_ADDR                                              0x00000000a4001014ULL


//
// Register:    REG_CHIPIO_DATA
// Size:        32-bits
// Type:        Read/Write
// Description: Reading this register returns the data from the most recent
//              chip-register read or write
//              
//              Data written to this register will be written to the chip-register
//              specified by CHIPIO_ADDR when a write command is issued via CHIPIO_CMD
//
#define REG_CHIPIO_DATA                                              0x00000000a4001018ULL


//
// Register:    REG_CHIPIO_CMD
// Size:        32-bits
// Type:        Read/Write
// Description: Write a command to begin a chip-register READ/WRITE:
//              1 = Read the value at chip-register address CHIPIO_ADDR
//              2 = Write CHIPIO_DATA to chip-register address CHIPIO_ADDR
//              5 = Same as 1, but auto-increments CHIPIO_ADDR by 4
//              6 = Same as 2, but auto-increments CHIPIO_ADDR by 4
//              Any other value = undefined behavior
//              
//              This register auto-clears to 0 when the read or write is complete
//
#define REG_CHIPIO_CMD                                               0x00000000a400101cULL


//
// Register:    REG_SMEM_BUSY
// Size:        32-bits
// Type:        Read only
// Description: Non-zero = SMEM is being updated
//
#define REG_SMEM_BUSY                                                0x00000000a4001024ULL


//
// Register:    REG_SMEM_ROWS_UPD
// Size:        32-bits
// Type:        Read only
// Description: The count of rows updated during the last SMEM update
//
#define REG_SMEM_ROWS_UPD                                            0x00000000a4001028ULL


//
// Register:    REG_SMEM_WORDS_UPD
// Size:        32-bits
// Type:        Read only
// Description: The count of 32-bit words updated during the last SMEM update
//
#define REG_SMEM_WORDS_UPD                                           0x00000000a400102cULL


//
// Register:    REG_ABM_COUNT
// Size:        32-bits
// Type:        Read/Write
// Description: The count of ABMs received.  Write any value to clear
//
#define REG_ABM_COUNT                                                0x00000000a4001030ULL


//
// Register:    REG_CHIP_PWR_ADC
// Size:        32-bits
// Type:        Read only
// Description: Array of 32 ADC readings
//
#define REG_CHIP_PWR_ADC                                             0x00000000a4002000ULL


//
// Register:    CHIP_REF_CLOCK
// Size:        32-bits
// Type:        Read only
// Description: HSI clock: reference frequency in Hz.
//
#define CHIP_REF_CLOCK                                               0x00000000a4003000ULL


//
// Register:    CHIP_CLOCK_VCO
// Size:        32-bits
// Type:        Read only
// Description: Chip Interface clock - VCO configuration.  See "Clock Configuration Register 0" in PG065.
//              
//              >                 REF_CLOCK * (clkfbout_mlt + clkfbout_frac/1000)
//              > VCO frequency = ------------------------------------------------
//              >                                 divclk_divide
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     divclk_divide                  8   07:00 RO   n/a         8-bit divide value of the reference clock
//     clkfbout_mult                  8   15:08 RO   n/a         Integer part of clock multiplier
//     clkfbout_frac                  10  25:16 RO   n/a         Fractional part of clock multiplier
//
#define CHIP_CLOCK_VCO                                               0x00000000a4003004ULL
#define CHIP_CLOCK_VCO_divclk_divide                                 0x08000000a4003004ULL
#define CHIP_CLOCK_VCO_clkfbout_mult                                 0x08080000a4003004ULL
#define CHIP_CLOCK_VCO_clkfbout_frac                                 0x0a100000a4003004ULL


//
// Register:    CHIP_CLOCK_DIV
// Size:        32-bits
// Type:        Read/Write
// Description: Chip interface clock - Frequency divider.  See "Clock Configuration Register 2" in PG065
//              ** Changing this value changes the frequency of the clock! **
//              
//              >                                   VCO frequency
//              >     clock frequency = ------------------------------------
//              >                       (clkout_divide + clockout_frac/1000)
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     clkout_divide                  8   07:00 RW   n/a         Integer portion of VCO divide value
//     clkout_frac                    10  17:08 RW   n/a         Fractional portion of VCO divide value
//
#define CHIP_CLOCK_DIV                                               0x00000000a4003008ULL
#define CHIP_CLOCK_DIV_clkout_divide                                 0x08000000a4003008ULL
#define CHIP_CLOCK_DIV_clkout_frac                                   0x0a080000a4003008ULL


//
// Register:    CHIP_FREQ_OUT
// Size:        32-bits
// Type:        Read only
// Description: The measured value of the chip interface clock, in Hz
//
#define CHIP_FREQ_OUT                                                0x00000000a400300cULL


//
// Register:    REG_CHIP_POWER_CTL
// Size:        32-bits
// Type:        Read/Write
// Description: Turn chip power on or off
//              1 to turn power on, 0 to turn power off
//
#define REG_CHIP_POWER_CTL                                           0x00000000a4004000ULL


//
// Register:    REG_CHIP_POWER_STATE
// Size:        32-bits
// Type:        Read only
// Description: Sensor chip power on state
//              1 = The sensor chip is on
//              0 = The sensor chip is off
//              After turning power on or off, it may take as moment
//              before that is reflected in this register
//
#define REG_CHIP_POWER_STATE                                         0x00000000a4004004ULL



#endif
