#
# The Versal VPK120 FPGA is xcvp1202-vsva2785-2MP-e-S
#

#
# Bitstream configuration
#
set_property BITSTREAM.GENERAL.COMPRESS TRUE  [current_design]

#
# PL UART
#
set_property -dict {PACKAGE_PIN V32  IOSTANDARD LVCMOS15}  [get_ports UART_txd]
set_property -dict {PACKAGE_PIN U32  IOSTANDARD LVCMOS15}  [get_ports UART_rxd]

 
#
#  UCI ADC bus - contains 3 LTC-1867L ADCs
#
set_property -dict {PACKAGE_PIN D28   IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports UCI_ADC_CSN[0]] ;# FMCP1_LA11_P
set_property -dict {PACKAGE_PIN C26   IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports UCI_ADC_CSN[1]] ;# FMCP1_LA13_N
set_property -dict {PACKAGE_PIN E26   IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports UCI_ADC_CSN[2]] ;# FMCP1_LA12_N
set_property -dict {PACKAGE_PIN E27   IOSTANDARD LVCMOS15           } [get_ports UCI_ADC_MISO  ] ;# FMCP1_LA12_P
set_property -dict {PACKAGE_PIN C27   IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports UCI_ADC_MOSI  ] ;# FMCP1_LA11_N
set_property -dict {PACKAGE_PIN B26   IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports UCI_ADC_SCK   ] ;# FMCP1_LA16_P


#
#  Chip power controls
#
set_property -dict {PACKAGE_PIN E23  IOSTANDARD LVCMOS15           } [get_ports CHIP_RSTB   ] ;# FMCP1_LA24_P
set_property -dict {PACKAGE_PIN D27  IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports CHIP_VDDIO  ] ;# FMCP1_LA13_P
set_property -dict {PACKAGE_PIN E21  IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports CHIP_VDDA   ] ;# FMCP1_LA32_N
set_property -dict {PACKAGE_PIN E22  IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports CHIP_VDDLVDS] ;# FMCP1_LA32_P
set_property -dict {PACKAGE_PIN C21  IOSTANDARD LVCMOS15  SLEW SLOW} [get_ports CHIP_VDD    ] ;# FMCP1_LA27_N



#
#  This enables a level translator for SPI pins on the sensor-chip (active low)
#
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS15   SLEW SLOW } [get_ports LVL_TRSL_OE_N] ;# FMCP1_LA30_N



#
# LVDS clock output to the sensor-chip. 768 MHz
#
set_property -dict {PACKAGE_PIN M28  IOSTANDARD LVDS15  DATA_RATE DDR  LVDS_PRE_EMPHASIS FALSE } [get_ports LVDS_CLK_clk_n] ;# FMCP1_LA02_N
set_property -dict {PACKAGE_PIN N27  IOSTANDARD LVDS15  DATA_RATE DDR  LVDS_PRE_EMPHASIS FALSE } [get_ports LVDS_CLK_clk_p] ;# FMCP1_LA02_P


#
# Constant signals and pa_sync
#
set_property -dict {PACKAGE_PIN G23   IOSTANDARD LVCMOS15 } [get_ports CHIP_GPIO15_DIR   ] ;# FMCP1_LA29_P
set_property -dict {PACKAGE_PIN N22   IOSTANDARD LVCMOS15 } [get_ports CHIP_GPIO13       ] ;# FMCP1_LA31_P
set_property -dict {PACKAGE_PIN N24   IOSTANDARD LVCMOS15 } [get_ports CHIP_GPIO15       ] ;# FMCP1_LA28_P
set_property -dict {PACKAGE_PIN D23   IOSTANDARD LVCMOS15 } [get_ports CHIP_GPIO_BYTE_DIR] ;# FMCP1_LA24_N
set_property -dict {PACKAGE_PIN M22   IOSTANDARD LVCMOS15 } [get_ports CHIP_RS0          ] ;# FMCP1_LA31_N  (CHIP_GPIO12)
set_property -dict {PACKAGE_PIN M23   IOSTANDARD LVCMOS15 } [get_ports CHIP_RS256        ] ;# FMCP1_LA28_N  (CHIP_GPIO14)
set_property -dict {PACKAGE_PIN N21   IOSTANDARD LVCMOS15 } [get_ports CHIP_PA_SYNC      ] ;# FMCP1_LA30_P  (CHIP_GPIO11)



#
# LVDS return clock
#
set_property -dict {PACKAGE_PIN D25  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_BANKA_clk_p]; # FMCP1_LA01_CC_P
set_property -dict {PACKAGE_PIN C25  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_BANKA_clk_n]; # FMCP1_LA01_CC_N


#
# LVDS data pins - positive
#
set_property -dict {PACKAGE_PIN R27  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 0] ]; # FMCP1_LA10_P
set_property -dict {PACKAGE_PIN R28  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 1] ]; # FMCP1_LA09_P
set_property -dict {PACKAGE_PIN H26  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 2] ]; # FMCP1_LA03_P
set_property -dict {PACKAGE_PIN F28  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 3] ]; # FMCP1_LA07_P
set_property -dict {PACKAGE_PIN F25  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 4] ]; # FMCP1_LA08_P
set_property -dict {PACKAGE_PIN V26  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 5] ]; # FMCP1_LA06_P
set_property -dict {PACKAGE_PIN H27  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 6] ]; # FMCP1_LA04_P
set_property -dict {PACKAGE_PIN T26  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DP[ 7] ]; # FMCP1_LA05_P


#
# LVDS data pins - negative
#
set_property -dict {PACKAGE_PIN P27  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 0] ]; # FMCP1_LA10_N
set_property -dict {PACKAGE_PIN P28  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 1] ]; # FMCP1_LA09_N
set_property -dict {PACKAGE_PIN G27  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 2] ]; # FMCP1_LA03_N
set_property -dict {PACKAGE_PIN E28  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 3] ]; # FMCP1_LA07_N
set_property -dict {PACKAGE_PIN E25  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 4] ]; # FMCP1_LA08_N
set_property -dict {PACKAGE_PIN U26  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 5] ]; # FMCP1_LA06_N
set_property -dict {PACKAGE_PIN G28  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 6] ]; # FMCP1_LA04_N
set_property -dict {PACKAGE_PIN R26  IOSTANDARD LVDS15  DATA_RATE DDR  DIFF_TERM_ADV TERM_100  EQUALIZATION EQ_LEVEL0} [get_ports LVDS_DN[ 7] ]; # FMCP1_LA05_N

